spring.application.name=HospitalAppointmentScheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_scheduler
spring.datasource.username=ayushagarwal
spring.datasource.password=ayush1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

server.port=${PORT:8080}